import '../../../shared/theme/app_sizes.dart';

class HomeSizes {
  static final double contentMaxWidth = toRem(24.5625);
  static final double horizontalPadding = toRem(0.9375);
  static final double headerPadding = toRem(0.5);
  static final double topPadding = toRem(0.625);
  static final double headerBottomGap = toRem(1.625);
  static final double settingsSize = toRem(3.75);
  static final double settingsIconWidth = toRem(1.85156875);
  static final double settingsIconHeight = toRem(1.89583125);
  static final double ecoHeight = toRem(15.4375);
  static final double ecoTopPadding = toRem(0.6875);
  static final double ecoSidePadding = toRem(0.625);
  static final double ecoBottomPadding = toRem(5);
  static final double ecoDecorationWidth = toRem(11.4375);
  static final double ecoDecorationHeight = toRem(10.4375);
  static final double badgeWidth = toRem(2.6875);
  static final double badgeHeight = toRem(2.75);
  static final double badgeFace = toRem(2.5625);
  static final double badgeTextInsetRight = toRem(0.125);
  static final double badgeTextInsetBottom = toRem(0.1875);
  static final double badgeTitleGap = toRem(0.375);
  static final double progressTopGap = toRem(0.4375);
  static final double progressSideInset = toRem(0.4375);
  static final double progressHeight = toRem(0.375);
  static final double progressRadius = toRem(0.3125);
  static const double progressFraction = 163 / 330;
  static final double ecoTileHeight = toRem(4.5);
  static final double ecoTileGap = toRem(0.6875);
  static final double separatorTopGap = toRem(1.5625);
  static final double separatorInset = toRem(1.25);
  static final double separatorHeight = toRem(0.25);
  static final double cardGap = toRem(1.25);
  static final double cardRowGap = toRem(1.3125);
  static final double cardHeight = toRem(9.375);
  static final double cardBottomPadding = toRem(0.75);
  static final double cardIconBox = toRem(3.4375);
  static final double carrotIcon = toRem(1.875);
  static final double recycleIcon = toRem(1.6875);
  static final double communityIconWidth = toRem(1.421875);
  static final double communityIconHeight = toRem(1.343825);
  static final double contentBottomGap = toRem(1.875);
  static final double navigationWidth = toRem(9.375);
  static final double navigationHeight = toRem(3.125);
  static final double navigationSlot = toRem(3.125);
  static final double navigationBottomGap = toRem(0.125);
  static final double thumbWidth = toRem(2.625);
  static final double thumbHeight = toRem(2.6875);
  static final double thumbFace = toRem(2.5);
  static final double mapIconWidth = toRem(1.09375625);
  static final double mapIconHeight = toRem(1.34375);
  static final double scanIcon = toRem(1.28125);
  static final double homeIconWidth = toRem(1.2187625);
  static final double homeIconHeight = toRem(1.28125);
  static const double dragThreshold = 0.6;
  static const Duration selectionDuration = Duration(milliseconds: 200);
  static const Duration destinationVisibilityDuration = Duration(seconds: 2);
  static const Duration resetDuration = Duration(milliseconds: 150);

  const HomeSizes._();
}
